(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const l=document.querySelector("#task-form"),a=document.querySelector("#task-list"),m=document.querySelector("#themeToggle");function u({title:t,description:e}){const r=`<li class="task-list-item">
              <button class="task-list-item-btn">Delete</button>
              <h3>${t}</h3>
              <p>${e}</p>
          </li>`;a.innerHTML+=r}function d(t){const e=JSON.parse(localStorage.getItem("tasks"))||[];e.push(t),localStorage.setItem("tasks",JSON.stringify(e))}function f(t){const r=JSON.parse(localStorage.getItem("tasks")).filter((i,s)=>s!==t);localStorage.setItem("tasks",JSON.stringify(r))}function g(){const t=JSON.parse(localStorage.getItem("tasks"))||[];a.innerHTML="";const e=t.map(({title:r,description:i})=>`
        <li class="task-list-item">
          <button class="task-list-item-btn">Delete</button>
          <h3>${r}</h3>
          <p>${i}</p>
        </li>`).join("");a.innerHTML=e}g();l.addEventListener("submit",h);function h(t){t.preventDefault();const e=t.target.taskName.value.trim(),r=t.target.taskDescription.value.trim();if(!e||!r){alert("Fill in all form fields");return}d({title:e,description:r}),u({title:e,description:r}),t.target.taskName.value="",t.target.taskDescription.value=""}a.addEventListener("click",t=>{if(!t.target.classList.contains("task-list-item-btn"))return;const e=t.target.closest(".task-list-item"),r=[...a.children].indexOf(e);f(r),e.remove()});const p=localStorage.getItem("theme")||"theme-dark";c(p);m.addEventListener("click",()=>{const e=(document.body.classList.contains("theme-light")?"theme-light":"theme-dark")==="theme-light"?"theme-dark":"theme-light";c(e),localStorage.setItem("theme",e)});function c(t){document.body.classList.remove("theme-dark","theme-light"),document.body.classList.add(t)}
//# sourceMappingURL=index.js.map
